    #pragma once

    #include "CoreMinimal.h"
    #include "UObject/NoExportTypes.h"
    #include "Perception/AISense_Hearing.h"
    #include "Perception/AISense_Sight.h"
    #include "Perception/AIPerceptionSystem.h"
    #include "Enumerators/Guard/AlertTypes.h"
    #include "InteractionData.generated.h"

    class UInteractableComponent;

    DECLARE_MULTICAST_DELEGATE(FOnInteractionEnded);

    UCLASS(Abstract, Blueprintable, EditInlineNew, DefaultToInstanced)
    class THEHEIST_API UInteractionData : public UObject
    {
        GENERATED_BODY()

    public:

        //--------------Functions

        //End of interaction event. Must be called whenever an interaction is over
        FOnInteractionEnded OnInteractionEnded;

    	//Set up the end sequence of each interaction
    	void EndOfInteraction();

        //Interaction execution. Must be overrided by each interaction type
        virtual void ExecuteInteraction(AActor* Owner, USceneComponent* Target);

        //Virtual function, to tick the UObject into the interaction component. Override this to make is happen
        virtual void Tick(float DeltaTime) {}

        
        //--------------Properties

        // Displayed text on the interaction widget
        UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Interaction")
        FString InteractText;
        
       
#pragma region Alert
        //-------------ALERT

        //--------------Alert Properties
        
        //Defines if the interaction can or cannot have an effect on the guard's behavior
        UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Alert")
        bool bCanAlertGuards = false;

        //Type of alert generated by the interaction
        UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Alert", meta = (EditCondition = "bCanAlertGuards"))
        EAlertTypes AlertType;

        // Range of the alert in units
        UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Alert", meta = (EditCondition = "bCanAlertGuards"))
        float AlertRadius = 500.f;

        // Loudness of the sound (only for Auditive alerts)
        UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Alert", meta = (EditCondition = "bCanAlertGuards && AlertType==EAlertType::Auditive"))
        float Loudness = 1.0f;

        
        UPROPERTY()
        class UAIPerceptionStimuliSourceComponent* StimulusSource;
        
        //-------------Alert Functions
        
        // Function to trigger guard's alert
        UFUNCTION(BlueprintCallable)
        void TriggerAlert(AActor* SourceActor);
        
        // Function to clear guard's alert
        UFUNCTION(BlueprintCallable)
        void ClearAlert(AActor* SourceActor);

#pragma endregion
        
        protected:
        
        //Hit Component by the user's interaction   
        UPROPERTY()
        USceneComponent* LinkedComponent = nullptr;
        
    };

    

    


    

    

    