    #pragma once

    #include "CoreMinimal.h"
    #include "UObject/NoExportTypes.h"
    #include "Perception/AISense_Hearing.h"
    #include "Perception/AISense_Sight.h"
    #include "Perception/AIPerceptionSystem.h"
    #include "Enumerators/Guard/AlertTypes.h"
    #include "InteractionData.generated.h"

    class UInteractableComponent;

    UCLASS(Abstract, Blueprintable, EditInlineNew)
    class THEHEIST_API UInteractionData : public UObject
    {
        GENERATED_BODY()

    public:

        //Defines if the interaction can or cannot have an effect on the guard's behavior
        UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Alert")
        bool bCanAlertGuards = false;
        
        // Function to trigger guard's alert
        UFUNCTION(BlueprintCallable, Category = "Alert")
        void TriggerAlert(AActor* SourceActor);
        
        // Function to clear guard's alert
        UFUNCTION(BlueprintCallable, Category = "Alert")
        void ClearAlert(AActor* SourceActor);
        
        // Range of the alert in units
        UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Alert", meta = (EditCondition = "bCanAlertGuards"))
        float AlertRadius = 500.f;

        // Loudness of the sound (only for Auditive alerts)
        UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Alert", meta = (EditCondition = "bCanAlertGuards && AlertType==EAlertType::Auditive"))
        float Loudness = 1.0f;
        
        //Type of alert generated by the interaction
        UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Alert")
        EAlertTypes AlertType;

        class UAIPerceptionStimuliSourceComponent* StimulusSource;
        
        // Displayed text on the interaction widget
        UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Interaction")
        FString InteractText;

        //Interaction execution. Overrided by each interaction type
        UFUNCTION(BlueprintNativeEvent, Category="Interaction")
        void ExecuteInteraction(AActor* Owner, USceneComponent* Target);

        //Virtual function, to tick the UObject into the interaction component. Override this to make is happen
        virtual void Tick(float DeltaTime) {}
        
        protected:

        //Hit Component by the user's interaction   
        UPROPERTY()
        USceneComponent* LinkedComponent = nullptr;
        
    };

    

    


    

    

    